---
title: "Case 1 Report 3"
author: "Jeffrey Ho, Amanda Levenberg, Lucy Lu"
date: "September 21, 2016"
output: pdf_document
---
**Background** - can someone please elaborate?

Through network modeling and analysis, this study aims to elucidate
whether a subject’s brain connectivity is associated with their level of openness, while controlling for confounding variables such as the age and sex of the subject. (??? - or was this just the purpose of the last report?)

**Introduction to the Model**

In order to model the probability of a connection between nodes for based on an individual's attributes, we fit a joint linear mixed effects model. With regards to the mixed-effects aspect of the link function, the model consists of two parts, fixed and random effects. The fixed effects, reprsented by $x_{i,u,v}^T$ include gender and an indicator of whether or not the two nodes are in the same hemisphere. On the other hand, the random effects we included are represented by $R_{i}^T$, which are age and level of openness.

- LUCY: please explain here why we put gender in fixed effects and age in random effects with wording maybe from that paper you got it from

Furthermore, using the probit as a link function enabled us to map a variable from the real line to a probability between 0 and 1. We chose probit instead of logit as the link function because ???

- probit approaches the axes more quickly than the logistic curve...
- to be honest, we could probably try to model both and see what we find...
- is it a problem that probit is supposed to map from the entire real line (negative infinity to infinity) to [0,1] as opposed to (0 to infinity) to [0,1]???

**Defining the Model and Parameters**

$$Pr(Y_{i,u,v}=1) = probit(\eta_{i,u,v})$$
$$\eta_{i,u,v} = x_{i,u,v}^T \beta + R_{i}^T b_{i} + \epsilon_{i,u,v}$$
$$x_{i,u,v} = (1, sex_{i}, I_{i,u,v}(hemisphere))^T$$

We define $I_{(i,u,v)}(hemisphere)$ to be the indicator function, as follows:
$$I_{(i,u,v)}(x)=
\begin{cases}
1\quad\text{if nodes $u$ and $v$ are in the same hemisphere (left or right) for person $i$}\\
0\quad\text{otherwise}
\end{cases}
$$
$$R_{i} = (1, age_{i}, openness_{i})^T$$
$$\beta_{k} \sim N(\theta_{k}, \psi_{k}); k=1,2,3$$
$$b_{i,j} \sim N(\mu_{j}, \Sigma_{j}); j=1,2,3$$
$$\epsilon_{i,u,v} \sim N(0, \sigma^2)$$

**Fitting the Model with Albert and Chib Sampling Algorithm**

We decided to use Albert and Chib's algorithm to sample because of the structure of the covariate data and response data. With the covariate data having both continuous and binary components and the response data being binary, an ordinary sampler could not be implemented. Therefore, we introduced a latent variable z to achieve semi-conjugacy and implement a Gibbs sampler. Below is the algorithm we implemented to approximate the joint posterior distribution.

1. Sample $\beta_{k}^0, b_{i,j}^0,$ and $\epsilon_{i,u,v}^0$ from their respective priors to obtain initial values.
2. Calculate $\eta_{i,u,v}^0$ and draw $z_{i,u,v}^0 \sim N(\eta_{i,u,v}, 1).$
3. After introducing a latent variable $z$, iteratively sample from the full conditionals, where t represents the iteration number:

$\beta_{k}^t \sim \pi(\beta_{k} | \beta_{-k}, b, \epsilon, y, z) \propto \pi(\beta_{k}*\prod_{i=1}^N \phi(z_{i,u,v}; \eta_{i,u,v}, 1) \sim N()$

$b_{i,j}^t \sim \pi(b_{i,j} | \beta, b_{-i,-j}, \epsilon, y, z) \propto \pi(b_{i,j}*\prod_{i=1}^N \phi(z_{i,u,v}; \eta_{i,u,v}, 1) \sim N()$

$\epsilon_{i,u,v} \sim \pi(\epsilon_{i,u,v} | \beta, b, \epsilon_{-i,u,v}, y, z) \propto \pi(\epsilon_{i,u,v}*\prod_{i=1}^N \phi(z_{i,u,v}; \eta_{i,u,v}, 1) \sim N()$

$z_{i,u,v} \sim N(\eta_{i,u,v}, 1)$ truncated at the left by 0 if $y_{i}=1$ and trunctaed at the right by 0 if $y_{i}=0$